### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JohnnyAmos** [SoRobby/ObsidianStarterVault#10]
Would you consider adding a license to the repository? Currently the default copyright law applies, which limits us to viewing and forking the code, but we could run into problems with the use of your code.

Thank you.

**Comment by SoRobby** [comment]
MIT license has been added to the repo.
Commit: [2be66d8 - Added MIT license](https://github.com/SoRobby/ObsidianStarterVault/commit/2be66d84abc78d643a3249469f6d69eaf95d95ec)

**Comment by JohnnyAmos** [comment]
Thank you!
