### ISSUE TITLE
Travel and Trip is not working

### ISSUE THREAD

**Issue by jidloyola** [SoRobby/ObsidianStarterVault#3]
Both the button and through templater don't work. It just says "maybe a file already exists?". I have not created any file yet.

**Comment by SoRobby** [comment]
@jidloyola The reported issue has been resolved in the latest release (v1.1).

Issue: The Templater file path to where the file was to be created did not exist which was resulting in this bug.

Releases: https://github.com/SoRobby/ObsidianStarterVault/releases
