### ISSUE TITLE
Notes Dahsboard - Overview over current Notes does not work

### ISSUE THREAD

**Issue by saurerzipfel** [SoRobby/ObsidianStarterVault#7]
Is it a known issue that the Collecttion of recent notes dataview table does not work correctly on the Notes Dashboard?
Looks like this in my Vault.
![problem-with-dataview-script-v0-qarfymuwp0ic1](https://github.com/SoRobby/ObsidianStarterVault/assets/103438776/3852a606-89ed-428a-a178-0f3ec182690f)

Really would appreciate a little help

**Comment by LucEast** [comment]
Hey @saurerzipfel. It looks like your theme might need an update.

**Comment by SoRobby** [comment]
Theme needed to be updated. When you first download and use this vault template, please make sure you update Obsidian, plugins, and themes.

**Comment by SoRobby** [comment]
Theme needed to be updated. When you first download and use this vault template, please make sure you update Obsidian, plugins, and themes.
